# Generated by Django 4.2.1 on 2023-07-26 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=40)),
                ('seat_count', models.CharField(max_length=5)),
                ('default_seat_count', models.CharField(max_length=5)),
                ('fare_rate', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('usertype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='other_places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_places_name', models.CharField(max_length=50)),
                ('other_places_type', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=40)),
                ('longitude', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=40)),
                ('longitude', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=50)),
                ('ending_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_ending', to='my_application.places')),
                ('starting_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_starting', to='my_application.places')),
            ],
        ),
        migrations.CreateModel(
            name='stationmaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('dob', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=40)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_application.login')),
            ],
        ),
        migrations.CreateModel(
            name='stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_application.places')),
                ('stationmaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_application.stationmaster')),
            ],
        ),
        migrations.CreateModel(
            name='trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_time', models.CharField(max_length=15)),
                ('ending_time', models.CharField(max_length=15)),
                ('no_of_stops', models.CharField(max_length=10)),
                ('trip_date', models.CharField(max_length=20)),
                ('trip_status', models.CharField(max_length=20)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_application.buses')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_application.routes')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_application.stations')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_conductor',
            fields=[
                ('conductor_id', models.AutoField(primary_key=True, serialize=False)),
                ('cfname', models.CharField(max_length=100)),
                ('clname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('cdob', models.CharField(max_length=100)),
                ('cphone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=40)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_application.buses')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_application.login')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_bus_location',
            fields=[
                ('location', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_application.buses')),
            ],
        ),
        migrations.CreateModel(
            name='tb_customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('dob', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_application.login')),
            ],
        ),
        migrations.CreateModel(
            name='tb_complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('complaint_date', models.CharField(max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_application.tb_customer')),
            ],
        ),
        migrations.CreateModel(
            name='stops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
                ('fare_rate', models.IntegerField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_application.places')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_application.trips')),
            ],
        ),
        migrations.AddField(
            model_name='routes',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_application.stations'),
        ),
        migrations.CreateModel(
            name='reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_seats', models.CharField(max_length=3)),
                ('reservation_amount', models.CharField(max_length=5)),
                ('reservation_status', models.CharField(max_length=15)),
                ('from_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_stop', to='my_application.stops')),
                ('to_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_stop', to='my_application.stops')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_application.trips')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_application.tb_customer')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=5)),
                ('payment_date', models.CharField(max_length=10)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_application.reservations')),
            ],
        ),
        migrations.AddField(
            model_name='buses',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_application.stations'),
        ),
    ]
